get-eventually/eventually-rs

Cargo.toml, eventually/Cargo.toml, eventually/examples/optional_person.rs, eventually/examples/optional_point.rs, eventually/examples/person.rs, eventually/examples/point.rs, eventually/src/aggregate/mod.rs, eventually/src/aggregate/optional.rs, eventually/src/aggregate/referential.rs, eventually/src/lib.rs
This PR adds the `Aggregate` trait to `eventually` crate.
`Aggregate` is a domain entity which state can be _created_, _mutated_ and _recreated_ by using **Domain Events**.
In order to fulfill these functionalities, an `Aggregate` implementation needs to provide an `apply` method (to apply the event to the current state).
Other traits and [_newtype-pattern_ adapters](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#using-the-newtype-pattern-to-implement-external-traits-on-external-types) are defined for ease of development in certain common scenarios, such as:
* `OptionalAggregate`: for `Aggregate` implementations where the aggregate state should be `Option<State>`
* `ReferentialAggregate`: for `Aggregate` implementations where the aggregate state should be `Self`, i.e. the …
=> eventually: implement Aggregate trait

.gitignore, Cargo.toml, eventually-memory/Cargo.toml, eventually-memory/benches/bench.rs, eventually-memory/src/lib.rs, eventually/Cargo.toml, eventually/examples/optional_point.rs, eventually/src/command/mod.rs, eventually/src/command/static.rs, eventually/src/lib.rs, eventually/src/store.rs
The proposed Event Store design is to have two separate traits:
- `ReadStore` for streaming persisted events
- `WriteStore` for committing new events
=> feat: add event store support

eventually/examples/optional_person.rs, eventually/examples/optional_point.rs, eventually/examples/person.rs, eventually/examples/point.rs, eventually/src/aggregate/mod.rs, eventually/src/aggregate/referential.rs, eventually/src/aggregate/util.rs, eventually/src/aggregate/versioned.rs
Add an `AggregateExt` supertrait extension with:
* `fn async_fold()` to fold an Aggregate given a `futures::Stream`
* `fn fold()`, previous implementation in `Aggregate` but now moved here
=> eventually: add AggregateExt supertrait

eventually-memory/src/lib.rs
The current implementation of `MemoryStore::stream` returns `futures::future::pending` in case the backing stream is empty.
This makes the `stream.collect::<Vec>().await` call hang on `await`, since the future will never complete.
Replace the `futures::future::pending` to `futures::future::empty`.
=> eventually-memory: fix stuck future on MemoryStore::stream

Cargo.toml, eventually-examples/Cargo.toml, eventually-examples/benches/bench.rs, eventually-examples/src/main.rs, eventually-examples/src/point.rs, eventually/src/command/dispatcher.rs, eventually/src/command/mod.rs, eventually/src/lib.rs
Now that we have `command::Handler` and `store::WriteStore`, we need a third piece of abstraction to:
* read the old events from the store
* recreate the `Aggregate` state
* call the `command::Handler` with the recreated state
* commit the new events to the store
This piece is called `Dispatcher` and lives in the `command::dispatcher` module.
This PR also includes an example-crate, `eventually-examples`, to showcase some possible applications of this crate.
=> feat: add command::dispatcher::Dispatcher

eventually-examples/Cargo.toml, eventually-examples/src/main.rs, eventually-examples/src/point.rs, eventually/Cargo.toml, eventually/examples/optional_point.rs, eventually/src/aggregate/mod.rs, eventually/src/command/mod.rs, eventually/src/command/static.rs, eventually/src/optional.rs, eventually/src/versioned.rs
Given the way `async/await` works, having the asynchronous result of `Handler::handle` in an associated type (`type Result`) is very cumbersome until we have GAT support.
The reason for it being the inability to specify the lifetime of the async block, that should capture the same lifetime as the `handle` method invocation.
As a solution, every `command::Handler` implementation should return, instead, a:
```
std::pin::Pin<Box<dyn std::future::Future<Output = T> + Send + 'async>>
```
or, using the `futures` crate, a `futures::future::BoxFuture` type.
Since writing the lifetimes in each `handle` method definition gets tiring very quickly, this PR introduces `async-trait` crate.
=> eventually: remove `type Result` from command::Handler

.cargo/config, eventually-core/src/aggregate.rs, eventually-core/src/command.rs, eventually-util/src/command/dispatcher.rs, eventually-util/src/optional.rs
Remove the current type alias bounds:
```rust
type MyBound<T: Bound> = T::Item;
```
to replace them with the supported version:
```rust
type MyBound<T> = <T as Bound>::Item;
```
This will lower warnings from the compiler.
=> chore: remove type alias bounds

eventually-core/Cargo.toml, eventually-core/src/aggregate.rs, eventually-core/src/command.rs, eventually-core/src/store.rs, eventually-examples/Cargo.toml, eventually-examples/src/point.rs, eventually-memory/Cargo.toml, eventually-memory/src/lib.rs, eventually-util/Cargo.toml, eventually-util/src/command/static.rs, eventually-util/src/optional.rs, eventually-util/src/versioned.rs, eventually/Cargo.toml, eventually/examples/optional_point.rs
In an effort to reduce the number of indirect dependencies introduced by the crate, the `async-trait`, albeit small, has been removed.
Replaced by explicit `futures::future::BoxFuture` return types and `Box::pin`-wrapped functions.
Also, `futures` has been pointed to `features = ["async-await"]`, to reduce the number of dependencies introduced by it.
=> chore: remove async-trait dependency

eventually-test/src/order.rs
Arguments for `map_or_else` are evaluated from left to right so move of `item` into `Vec::push` occurs before `map` closure evaluation and borrowck thinks that `items` is no longer accessible.
We can copy `quantity` field of `item` before `iter_mut` block with `let` binding or use `map` first and then `or_else` later.
=> Fix OrderItems method

eventually-core/src/repository.rs, eventually-core/src/store.rs, eventually-postgres/src/lib.rs, eventually-test/src/api.rs, eventually-test/src/main.rs, eventually-test/src/state.rs, eventually-util/Cargo.toml, eventually-util/benches/event-store-inmemory-bench.rs, eventually-util/src/inmemory.rs
Closes #62 
**NOTE:** this PR breaks `eventually-postgres`, which should go on a full overhaul.
=> feat: move versioning check on the EventStore

eventually-core/src/projection.rs, eventually-test/src/api.rs, eventually-test/src/lib.rs, eventually-test/src/order.rs, eventually-util/src/inmemory/projector.rs, eventually-util/src/inmemory/store.rs
Related to #93
Projections should fully own the data storage method used.
Considering these storage might be (most likely) external database (e.g. Postgres tables), the trait's `project` method has to become a `Future`, and might potentially fail in case of connection error.
=> feat: Projection trait is now async and might fail

eventually-postgres/Cargo.toml, eventually-postgres/src/lib.rs, eventually/Cargo.toml, eventually/src/lib.rs
Expose the `eventually-postgres` crate through the `postgres` feature flag in the `eventually` public API crate.
=> eventually: add 'postgres' feature flag

eventually-postgres/src/subscription.rs, eventually-postgres/tests/subscriber.rs
When creating new empty Persistent Subscriptions on Postgres, the previous checkpoint code would panic, due to an unchecked `i64` to `u32` conversion.
=> fix(eventually-postgres): overflow caused by i64 to u32 conversion

.github/workflows/rust.yml
makes sense to use the nightly toolchain for linting, though there's one caveat-
Clippy should really have a config file that specifies a MSRV (this project doesn't seem to specify one) in order to prevent it trying to apply lints that don't yet apply to stable (i've not seen this actually happen before, but in principle it's possible)
=> use nightly toolchain for linting and formatting

eventually-core/src/subscription.rs, eventually-postgres/src/subscriber.rs, eventually-postgres/src/subscription.rs, eventually-postgres/tests/subscriber.rs, eventually-redis/src/subscriber.rs, eventually-redis/tests/store.rs, eventually-util/src/inmemory/store.rs
since `EventSubscriber::subscribe_all` returns a `TryFuture<TryStream<_, Error>, Error>` (ie they both have the same error type) this can be flattened into a `TryStream` alone.
=> simplify 'EventSubscriber::subscribe_all'

eventually-core/src/subscription.rs, eventually-postgres/Cargo.toml, eventually-postgres/src/subscription.rs, eventually-postgres/tests/subscriber.rs, eventually-redis/src/subscription.rs, eventually-util/src/inmemory/projector.rs
similarly to #167, the `Future` returning a `Stream` can be flattened into a stream since they share the same error type
=> Simplify 'Subscription' trait

eventually-postgres/src/lib.rs, eventually-postgres/src/store.rs, eventually-postgres/src/subscription.rs, eventually-redis/src/lib.rs, eventually-redis/src/store.rs, eventually-redis/src/subscriber.rs, eventually-redis/src/subscription.rs, eventually/src/store.rs, eventually/src/subscription.rs, eventually/src/util.rs, eventually/src/util/inmemory/mod.rs, eventually/src/util/inmemory/store.rs, eventually/src/util/optional.rs
What it says on the tin ;)
this PR
- moves the compiler flags from a cargo config file to inline compiler flags (which i believe is generally preferred). 
- adds the `deny(clippy::all)` lint flag, which is a stricter linting configuration than was applied previously. this necessitated a couple of code changes to appease the stricter lint.
- fixes a couple of `clippy::pedantic` lints (though i've not enabled the flag for this)
=> Apply stricter lint configuration

eventually/src/aggregate.rs, eventually/src/command.rs, eventually/src/event.rs, eventually/src/lib.rs, eventually/src/message.rs, eventually/src/test/command_handler.rs, eventually/src/test/store.rs
To pass down the name of Commands and Domain Events to potential Event Stores that use them, a `message::Payload` trait has been introduced.
The trait requires a `Message` inner payload to implement a `fn name(&self) -> &'static str` method to return its name.
What's more, this PR also modifies the `aggregate::Root` trait, which is now requiring `Borrow<Context>` and `BorrowMut<Context>` to cover the previous `fn ctx(&self) -> &Context` and `fn ctx_mut(&mut self) -> &mut Context` functions.
=> [v0.5.0][eventually] Introduce message::Payload trait

eventually/src/aggregate.rs, eventually/src/command.rs, eventually/src/event.rs, eventually/src/message.rs, eventually/src/test/command_handler.rs, eventually/src/test/store.rs, examples/bank-accounting/src/application.rs, examples/bank-accounting/src/domain.rs
As the title says, this PR renames `message::Payload` trait into `message::Message`, and `message::Message` into `message::Envelope`
=> [v0.5.0] refactor: rename message::Payload to Message and Message to Envelope

eventually/src/aggregate.rs, eventually/src/aggregate/repository.rs, eventually/src/aggregate/root.rs, examples/bank-accounting/src/domain.rs
- [v0.5.0][eventually] refactor: message::Metadata is now map<string, string>
- [v0.5.0][eventually] refactor: make aggregate::Root easier to use
=> [v0.5.0][eventually] refactor: make aggregate::Root easier to use

eventually/src/command.rs, eventually/src/test/command_handler.rs, examples/bank-accounting/src/application.rs
The current API for `eventually::test::command_handler::Scenario` uses static methods, which look somewhat like this:
```rust
eventually::test::command_handler::Scenario::given(vec![
// ...
])
```
This PR refactors this API by changing those methods to take `self`, resulting in the following API:
```rust
eventually::test::command_handler::Scenario
.given(vec![
// ...
])
.when(...)
.then(...)
.assert_on(...)
```
=> [v0.5.0][eventually] refactor: use by-value methods for command_handler::Scenario API

.github/workflows/docs.yml
With the previous merge of #231 and the update of `tonic`, the Generate Docs pipeline is now failing due to missing `protoc`.
This PR fixes the issue by adding `protoc` during the action container setup steps.
=> fix(.github): add protoc to generate docs pipeline

README.md
Changes the link to an example use of `eventually` in the repo's README.
=> chore(docs): change link to example 

.github/workflows/ci.yml
`llvm-cov` is better maintained, and supports doc-tests coverage
=> update coverage workflow

.editorconfig, CONTRIBUTING.md, eventually-postgres/src/aggregate.rs, eventually-postgres/tests/aggregate_repository.rs, eventually-postgres/tests/event_store.rs, eventually/src/aggregate.rs, eventually/src/aggregate/repository.rs, eventually/src/command.rs, eventually/src/tracing.rs, examples/bank-accounting/src/application.rs, examples/bank-accounting/src/grpc.rs
- refactor: rename aggregate::Saver::store in aggregate::Saver::save
- refactor: move aggregate::{Saver, Getter} to aggregate::repository::{Getter, Saver}
- feat: add .editorconfig
- chore: update CONTRIBUTING.md guidelines doc
=> refactor: rename aggregate::Saver method, move repositories into aggregate::repository mod

eventually-postgres/src/event.rs, eventually-postgres/tests/event_store.rs
- fix(event): remove trailing parenthesis from AppendError
- fix(tests/event_store): use if-let-else for result assertion in case of concurrency
=> fix(eventually-postgres): flaky integration test for event_store.rs

Cargo.toml, examples/light-switch/Cargo.toml, examples/light-switch/README.md, examples/light-switch/src/application.rs, examples/light-switch/src/commands/install_light_switch.rs, examples/light-switch/src/commands/mod.rs, examples/light-switch/src/commands/turn_light_switch_off.rs, examples/light-switch/src/commands/turn_light_switch_on.rs, examples/light-switch/src/domain.rs, examples/light-switch/src/main.rs, examples/light-switch/src/queries/get_switch_state.rs, examples/light-switch/src/queries/mod.rs
This example application is a bare minimum example of the core functionality. Persistence is not enabled, nor is logging, nor any kind of user interface. It just starts, runs some commands, queries the final state and prints it.
It models a "light switch". You can "install" the switch, then turn it "off" or "on" using commands. You can issue a query to get the current state of a switch.
=> feat(examples): bare minimum "light switch" example
